-- Run with `insforge db import database/schema.sql`. Never expose an InsForge admin key in the browser.
create extension if not exists pgcrypto;
create type public.user_role as enum ('admin'); create type public.enquiry_status as enum ('new','contacted','quoted','completed','cancelled');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'admin', full_name text, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, image_url text, image_key text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, category_id uuid references public.categories(id) on delete set null, short_description text, description text, features jsonb not null default '[]', applications jsonb not null default '[]', specifications jsonb not null default '{}', featured boolean not null default false, published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, image_url text not null, image_key text, alt_text text, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.laser_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.materials (id uuid primary key default gen_random_uuid(), name text not null unique, active boolean not null default true, created_at timestamptz not null default now());
create table public.laser_projects (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, description text, category_id uuid references public.laser_categories(id) on delete set null, material text, featured boolean not null default false, published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.laser_project_images (id uuid primary key default gen_random_uuid(), laser_project_id uuid not null references public.laser_projects(id) on delete cascade, image_url text not null, image_key text, alt_text text, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.gallery (id uuid primary key default gen_random_uuid(), title text, category text not null default 'Machinery', description text, image_url text not null, image_key text, alt_text text, sort_order integer not null default 0, published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.enquiries (id uuid primary key default gen_random_uuid(), name text not null, phone text not null, email text, company text, type text not null, requirement_type text, product text, quantity text, material text, description text not null, status public.enquiry_status not null default 'new', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.enquiry_files (id uuid primary key default gen_random_uuid(), enquiry_id uuid not null references public.enquiries(id) on delete cascade, file_path text not null, file_name text not null, file_type text, file_size bigint, created_at timestamptz not null default now());
create table public.site_settings (id smallint primary key default 1 check (id=1), business_name text not null default 'S.P. AGRO', phone text, whatsapp text, email text, address text not null default 'Near Shital Pump, Babhaleshwar Kh., Maharashtra - 413737, India', business_hours text, maps_url text, hero_heading text not null default 'Built for Agriculture. Made with Precision.', hero_subtitle text not null default 'Reliable agricultural machinery and precision laser cutting solutions for farmers, fabricators and industries.', about_text text, footer_text text, updated_at timestamptz not null default now());insert into public.site_settings(id) values(1) on conflict do nothing;
create index products_published_idx on public.products(published,featured);create index products_category_idx on public.products(category_id);create index gallery_published_idx on public.gallery(published,sort_order);create index enquiries_status_idx on public.enquiries(status,created_at desc);
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
create or replace function public.update_timestamp() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end; $$;
create trigger products_timestamp before update on public.products for each row execute function public.update_timestamp();create trigger gallery_timestamp before update on public.gallery for each row execute function public.update_timestamp();create trigger enquiries_timestamp before update on public.enquiries for each row execute function public.update_timestamp();
alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.products enable row level security;alter table public.product_images enable row level security;alter table public.laser_categories enable row level security;alter table public.materials enable row level security;alter table public.laser_projects enable row level security;alter table public.laser_project_images enable row level security;alter table public.gallery enable row level security;alter table public.enquiries enable row level security;alter table public.enquiry_files enable row level security;alter table public.site_settings enable row level security;
create policy "public published products" on public.products for select using(published or public.is_admin());create policy "public product images" on public.product_images for select using(exists(select 1 from public.products p where p.id=product_id and (p.published or public.is_admin())));create policy "public categories" on public.categories for select using(active or public.is_admin());create policy "public laser projects" on public.laser_projects for select using(published or public.is_admin());create policy "public laser images" on public.laser_project_images for select using(exists(select 1 from public.laser_projects p where p.id=laser_project_id and (p.published or public.is_admin())));create policy "public gallery" on public.gallery for select using(published or public.is_admin());create policy "public settings" on public.site_settings for select using(true);create policy "public materials" on public.materials for select using(active or public.is_admin());create policy "public laser categories" on public.laser_categories for select using(active or public.is_admin());
create policy "admins manage profiles" on public.profiles for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage categories" on public.categories for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage products" on public.products for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage product images" on public.product_images for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage laser categories" on public.laser_categories for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage materials" on public.materials for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage laser projects" on public.laser_projects for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage laser images" on public.laser_project_images for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage gallery" on public.gallery for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage enquiries" on public.enquiries for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage enquiry files" on public.enquiry_files for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage settings" on public.site_settings for update using(public.is_admin()) with check(public.is_admin());
-- Create public buckets named product-images, laser-images and gallery-images; create enquiry-files as private.
