import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Menu, MessageCircle } from "lucide-react";
import { getSettings } from "@/lib/catalogue";
import { getWhatsAppUrl } from "@/lib/whatsapp";
const links = [["About","/about"],["Machinery","/machinery"],["Laser Cutting","/laser-cutting"],["Custom Solutions","/custom-solutions"],["Gallery","/gallery"],["Contact","/contact"]] as const;
export function Brand(){return <Link href="/" aria-label="S.P. AGRO home" style={{display:"inline-flex",alignItems:"center",gap:9,height:64,flexShrink:0}}><Image src="/sp-agro-logo.png" alt="S.P. AGRO gear logo" width={1400} height={1024} priority style={{width:46,height:46,objectFit:"contain"}}/><span style={{display:"grid",gap:2,textAlign:"left",lineHeight:1}}><b style={{fontSize:"1.12rem",letterSpacing:"-.04em"}}>S.P AGRO</b><small style={{fontSize:".48rem",letterSpacing:".12em",color:"#627068",whiteSpace:"nowrap"}}>AGRICULTURAL MACHINERY</small></span></Link>}
export async function SiteHeader(){return <header style={{position:"sticky",top:0,zIndex:50,background:"#f5f7f4ed",backdropFilter:"blur(12px)",borderBottom:"1px solid #d9e1da"}}><div className="shell" style={{height:82,display:"flex",alignItems:"center",justifyContent:"space-between",gap:20}}><Brand/><nav className="desktop-nav" aria-label="Main navigation" style={{display:"flex",gap:20,fontSize:".85rem",fontWeight:650}}>{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><Link className="button button-accent desktop-nav" href="/quote">Get a Quote <ArrowUpRight size={16}/></Link><details className="mobile-nav"><summary aria-label="Open navigation" style={{listStyle:"none",cursor:"pointer"}}><Menu/></summary><nav style={{position:"absolute",right:16,top:74,display:"grid",gap:14,padding:20,background:"white",border:"1px solid #d9e1da",minWidth:210}}>{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link className="button button-accent" href="/quote">Get a Quote</Link></nav></details></div></header>}
export async function SiteFooter(){const s=await getSettings();const whats=getWhatsAppUrl(s.whatsapp,"Hello S.P. AGRO, I would like to know more.");return <footer style={{background:"#14251c",color:"#eef2ed",padding:"4.5rem 0 1.5rem",marginTop:"5rem"}}><div className="shell" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:34}}><div><Brand/><p style={{color:"#b5c1b8",lineHeight:1.65,maxWidth:240}}>{s.footer_text}</p></div><div><b>Explore</b><div style={{display:"grid",gap:9,marginTop:15,color:"#cbd3ca"}}>{links.slice(1).map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link href="/admin">Admin login</Link></div></div><div><b>Visit or contact</b><p style={{color:"#cbd3ca",lineHeight:1.65}}>{s.address}</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Link className="button button-accent" href={whats}><MessageCircle size={16}/> WhatsApp</Link><Link className="button button-outline" style={{color:"white",borderColor:"#607467"}} href="/contact">Contact</Link></div></div></div><div className="shell" style={{marginTop:40,paddingTop:18,borderTop:"1px solid #ffffff1c",color:"#8ea095",fontSize:".8rem"}}>© {new Date().getFullYear()} S.P. AGRO. All rights reserved.</div></footer>}
